name: Build and Publish Docker Image

on:
  push:
    branches:
      - master
      - development
    tags:
      - 'v*' # Matches tags like v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Log in to Docker Hub (only if on master branch or tag)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Log in to GitHub Container Registry (only if on master branch or tag)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          # List of Docker images to use as base name for tags
          images: |
            ${{ env.OWNER }}/${{ env.REPOSITORY }}
            ghcr.io/${{ env.OWNER }}/${{ env.REPOSITORY }}
          # Generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{raw}}
            type=edge,branch=${{ github.event.repository.default_branch }}
            type=edge,branch=development,suffix=-dev
        env:
          OWNER: "${{ github.repository_owner }}"
          REPOSITORY: "${{ github.event.repository.name }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
